git:
  pagers:
    - colorArg: always
      pager: delta -s --dark --paging=never --24-bit-color=never
gui:
  theme:
    activeBorderColor:
      - '#f5a97f'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#a6da95'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  authorColors:
    '*': '#b7bdf8'
os:
  edit: "nvim --server $NVIM --remote {{filename}}"
  editAtLine: "nvim --server $NVIM --remote {{filename}}; nvim --server $NVIM --remote-send ':{{line}}<CR>'"
  editInTerminal: false
customCommands:
  - key: 'G'
    context: 'global'
    command: "git gone"
